# Aves Configuration
# you can delete this file
# or use command `flutter pub run aves init:config` to generate new one

# main command for run flutter: 'flutter' or 'fvm'
command: fvm

# 'none', 'overwrite'
delete-conflicting-outputs: none

template:
#  logic: assets/my_logic.template
#  view: assets/my_view.template
#  model: assets/my_model.template